### ISSUE TITLE
Select does not work

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#11]
Code from example page. When item is selected there is error:

```
[Vue warn]: Error in render: "TypeError: r.a.compile is not a function"
found in
---> <Render> at src/render.vue
       <VaButton> at src/Button/VaButton.vue
         <VaSelect> at src/Select/VaSelect.vue
```

**Comment by nvms** [comment]
Hi,

At http://vue-atlas.com/documentation/select ? I'm not able to reproduce that error. Which props, if any, do you have selected when that appears?

**Comment by max-frai** [comment]
@nvms no, it works on vue-atlas, but try to create empty new project with latest vue-atlas and insert this simple code:

```
<va-select v-model="simpleValue" placeholder="Pick one" no-uncheck>
  <va-option value="one">1</va-option>
  <va-option value="two">2</va-option>
  <va-option value="three">3</va-option>
</va-select>
```
It will render okay, but when you try to select some item, rendering breaks with that error

**Comment by nvms** [comment]
@max-frai I created a new webpack project using 'vue-init webpack <project>', installed the latest vue-atlas (1.1.18) and instanced a Select component without issue. I'm not seeing any errors.

How did you create your empty new project?

**Comment by max-frai** [comment]
Hello again, sorry for long response!
It seems that you are using vue with runtime + compiler build and in my case there is only runtime.
https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only
I digg into source and found that you are using `template` field manually which requires vue to render component on client side during call. Without this everything is precompiled to js.

So I think we should clarify in docs that compiler is required or maybe rewrite element without `template` usage.

**Comment by nvms** [comment]
It sounds like you cloned the atlas repo and have included the .vue single-file components into your project, is that true?

**Comment by nvms** [comment]
@max-frai Oh! Yes! Very good point. I will update the documentation. The compiler is currently needed for the Select component at this point in time.

Thank you for catching that!
