### ISSUE TITLE
Select visualization with lots of long selects is broken

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#119]
**What version of vue-atlas are you using?**
latest

**Steps to reproduce:**
Select with fixed width and long labels has text overflow.
I'm not sure what's the best way to fix this. How it's processed in other ui libraries?
<img width="536" alt="default" src="https://user-images.githubusercontent.com/24208746/53425357-81400680-39ed-11e9-8a53-39b6bf1afe2c.png">

**Comment by nvms** [comment]
I think usually what happens is that the items begin again on the line below, like this:

<img width="309" alt="screen shot 2019-02-26 at 8 48 59 am" src="https://user-images.githubusercontent.com/17074357/53430478-72346680-39a3-11e9-8683-267326d53c5e.png">

this is a small CSS change. `div.va-btn-text-fade` needs `white-space: normal;`

**Comment by max-frai** [comment]
Hello! So, can you merge this fix into master and make a release? Or there is something wrong with this?

**Comment by max-frai** [comment]
Also, will it fix the following case? When buttons in one form item are side to side. Is it possible to allow them go to newline?
<img width="562" alt="изображение" src="https://user-images.githubusercontent.com/24208746/59938879-f03ee080-945e-11e9-9eb5-c830409a52fc.png">

**Comment by nvms** [comment]
in this use-case, are you not able to use a form-item for each button?

to answer your question: the fix for the select item wrapping above will not affect the flow of the buttons as you show above

**Comment by max-frai** [comment]
There is a lot of this buttons, so I can't put them on new line each. The best way is to fit as possible and break newline for other items

**Comment by max-frai** [comment]
I found that possible solution is to use flex-wrap. Maybe there is sense to add this into va-flex or other common style in form.
<img width="357" alt="изображение" src="https://user-images.githubusercontent.com/24208746/59939496-cdadc700-9460-11e9-9a85-967614a3a6f8.png">

**Comment by nvms** [comment]
I will look into applying a flex-wrap to the va-form-item. if it doesn't break anything else, this might be a good overall solution.

this issue can finally be closed as it is fixed in f1573dc - will be pushing a release shortly
