### ISSUE TITLE
give "name" attribute to form inputs

### ISSUE THREAD

**Issue by SamuelRiversMoore** [nvms/vue-atlas#12]
We need `name` attributes in form inputs in order to be able to serialize form datas with the `new FormData(myForm)` method.

The `name` prop exists inside `inputMixins.js` but the VaInput, VaCheckbox, VaRadio, VaRange, etc. components doesn't have their `name` attribute defined by their name prop ( `:name="name"` ).

For the VaSelect component it's another issue since this component doesn't have any input inside...

**Comment by nvms** [comment]
nice catch. I have a potential solution for the VaSelect component that I'll mention in the other issue. I'll close this as I'll be merging your PR with these changes shortly.
