### ISSUE TITLE
Relative module not found when importing single component (DatePicker) => ../position

### ISSUE THREAD

**Issue by chadoc** [nvms/vue-atlas#124]
**What version of vue-atlas are you using?**
2.0.13

**Steps to reproduce:**
1. Import VaDatePicker in single component mode and use it:
`
import 'vue-atlas/dist/vue-atlas.css'
import VaDatePicker from 'vue-atlas/src/Datepicker'
`
2. yarn install

**What is expected?**
We should be able to use the component in single mode.

**What is actually happening?**
` ERROR  Failed to compile with 2 errors                                                                                                                                                                                               15:18:04

This relative module was not found:

* ../position in ./node_modules/vue-atlas/src/Datepicker/install.js
`

**Any additional comments? (optional)**
-

**Comment by nvms** [comment]
fixed in #125 (thanks again for the PR)
