### ISSUE TITLE
Button instead of anchor

### ISSUE THREAD

**Issue by thefoxie** [nvms/vue-atlas#128]
**Please describe the feature in detail:**
Change va-button to use `<button>` instead of `<a>`

**Would this be a breaking change?**
Might be, potentially.

**What problem does this feature solve?**
Semantics and accesibility?

**Comment by nvms** [comment]
good idea

I'm pretty confident that this is not a breaking change.

will do some testing and probably get this out today

**Comment by nvms** [comment]
7f941e8
