### ISSUE TITLE
Non trivial values for Select

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#129]
Hello, I use mongodb on backend and it returns json serialized ids in format: 

`{ "$oid" : "5d0a8e434fbfc03dc800aa2f" }`

I use such objects as value for select items. So when I select options manually, it works okay and also stores this structure into model variable. But when I want to set this value by code it does not work:

`model_variable: [{"$oid":"5d0a8e434fbfc03dc800aa2f"}]`

With vue debugger I see inside select's state that it stores this value inside, but it does not 'think' that this option is selected.

Is it possible to use non trivial object as keys? Maybe use hash to identify options?

I can remove "$oid" part and save objectid directly, but then I should convert it back when send to backend again.

**Comment by max-frai** [comment]
I found the problem is here on line **408**, here we try to compare two objects like this:
`{$oid: "5cfce855833bb51a2f59e243"} === {$oid: "5cfce855833bb51a2f59e243"}`
And, of course, it's always false. There is a way to try compare json stringify == json stringify. Is it okay solution for you? This will allow to use complex values inside select component.

https://github.com/nvms/vue-atlas/blob/4f11d8468d1666e4cc4a20e5371687ee9e1e3216/src/Select/VaSelect.vue#L405-L413

**Comment by max-frai** [comment]
I checked changes locally on test App, it works okay. But I failed to replace my local build with installed by npm in my project :( So I don't know how to continue work on real project with my changes

**Comment by max-frai** [comment]
When I try to use my build after 'publish.sh' it results in following error:
`vue__WEBPACK_IMPORTED_MODULE_0__.default.prototype.notification is undefined`

Can't understand what's difference and how to build it.

**Comment by nvms** [comment]
fixed in the latest release: 2.0.14
