### ISSUE TITLE
What's the correct way to show sidebar on mobile?

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#132]
Hello, I tried to understand it from docs, because there you have such functionality, but there is no description what's the right way to do it.
I tried to set `mobile-sidebar-width` to some number on click at button in topbar on mobiles, but it seems that sidebar is not usable on mobiles.

Thank you.

**Comment by nvms** [comment]
The `App` component allows you to define both desktop and mobile values for `Sidebar`, `Topbar` and `Minibar`. Prop names are:

`desktopSidebarWidth`, `desktopMinibarWidth` and `desktopTopbarHeight`.

For mobile:

`mobileSidebarWidth`, `mobileMinibarWidth` and `mobileTopbarHeight`.

The `App` component has a `mobileBreakpoint` prop. Default value is `768`. The `App` component listens for the window's resize event. When the width of the window is larger than `mobileBreakpoint`, `desktopSidebarWidth`, `desktopMinibarWidth` and `desktopTopbarHeight` are used. When the width of the window is _smaller_ than `mobileBreakpoint`, the mobile values are used.

`App` does not inspect UA strings or anything like that. Mobile detection is based purely on window width. I'm open to suggestions for better ways to handle this, or improvements.

I hope this answers your question!

**Comment by max-frai** [comment]
Hello, thank you for response. I think it's okay approach, but the question is about something other.
We can detect if we are on mobile, also we can change sizing for different elements based on this.
In docs page (vue-atlas.com) on mobile version you have burger-button in topbar. On click the sidebar appears fullscreen.
The question is how you made this logic? What's code of round burger button click?

If I just change `mobile-sidebar-width` it does not appear over current content.

**Comment by nvms** [comment]
Yes, of course. You'll want to check out the `Mobile` and `Desktop` components:

http://vue-atlas.com/documentation/mobile
http://vue-atlas.com/documentation/desktop

**Comment by nvms** [comment]
On mobile, I simply toggle the value passed to `mobileSidebarWidth` between 0px and 100% of the window width when the button is clicked.

**Comment by max-frai** [comment]
Okay, that's what I wanted to hear. Thank you.
