### ISSUE TITLE
A lot of errors for va-input and getBoundingClientRect

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#133]
I have a lot of components in sidebar, they have lots of va-input and sometimes it starts to throw this error:
<img width="578" alt="изображение" src="https://user-images.githubusercontent.com/24208746/60726441-38243400-9f44-11e9-9c12-c6ffcb697659.png">

<img width="483" alt="изображение" src="https://user-images.githubusercontent.com/24208746/60726500-60139780-9f44-11e9-9f0a-f2493c6bee60.png">

Maybe you know what could be a reason?

**Comment by nvms** [comment]
do the errors only appear when resizing or scrolling the page?

**Comment by nvms** [comment]
in bfab8a476ba7f8c1091351eacb2259d4d529a68a, the window resize event listener that called `setPosition` is now destroyed in `beforeDestroy` (it was not before, whoops) - I wonder if this will fix the issue?

**Comment by max-frai** [comment]
Now it seems disappeared! Thank you. Hope for release with fix for textarea validation and this ♥️

**Comment by nvms** [comment]
forgot to close this - was fixed in 2.0.15.

thanks for the issue!

**Comment by max-frai** [comment]
Also, if you are interested, here is my use case of your library:
https://www.reddit.com/r/rust/comments/cdg5b4/rust_in_the_on_of_the_biggest_music_festival/

All frontend of system in the article is written with vue-atlas ;)

**Comment by nvms** [comment]
MAX!

this is the coolest thing I've seen so far built with this library. I really hope it met your needs. thanks for sharing this! made my day.
