### ISSUE TITLE
CSS breaking surrounding page

### ISSUE THREAD

**Issue by Daywalker999** [nvms/vue-atlas#134]
**What version of vue-atlas are you using?**
2.0.14

**Steps to reproduce:**

1. Build a page with vue.js and include in existing atlassian environment
2. Use scoped css and import "~vue-atlas/dist/vue-atlas.css"

**What is expected?**
Vue-atlas components should not break the surrounding page

**What is actually happening?**
vue-atlas component is breaking the surrounding page

**Any additional comments? (optional)**
I use vue-atlas for Jira plugin development. So i can develop my ui in vue.js but it looks like i'm using AUI. When i import the vue-altas css into my vue component it is breaking jira's css.

See: https://imgur.com/a/6lMTquk

I'd like to know if there is any way, to scope the css only to the vue-atlas components but not the entire page.

**Comment by nvms** [comment]
I left those globally-defined anchor tag styles in for convenience, but your use case makes me think it was a bad idea.

I will modify the selector to only target anchor tags inside of a `VaPage`, to preserve some convenience but also to not clutter global style space.

will push a release with this soon (2.0.16), as I'm not sure what the best way for you to get around this in the meantime would be

**Comment by nvms** [comment]
upgrading to the latest release should fix this specific issue.

I'm interested in hearing more about your usage with this project. it seems quite interesting! please do let me know if you run into any other oddities. thanks

**Comment by Daywalker999** [comment]
Thank you. I will respond as soon as i've tested this.

**Comment by Daywalker999** [comment]
It's looking good so far but i found one thing:
The Jira Logo and badges are visibly picking up this rule from the vue css:
`
*, :after, :before {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}`

which results in smaller badges and a a messed up logo.

**Comment by nvms** [comment]
ah yes, will get this one fixed soon as well
