### ISSUE TITLE
Undefined variable: "$class-prefix".

### ISSUE THREAD

**Issue by tywldx** [nvms/vue-atlas#135]
**What version of vue-atlas are you using?**
vue-atlas version: 2.0.17
vue version: 3.5.1
**Steps to reproduce:**
1.  
```
vue new projectname
```
2. 
```
npm install vue-atlas
```
3. [Import individual components](https://vue-atlas.com/documentation/introduction#installation)
4. 
```
npm run serve
```

**What is expected?**
run success
**What is actually happening?**
```
error  in ./node_modules/vue-atlas/src/Button/VaButton.vue?vue&type=style&index=0&lang=scss&

Module build failed (from ./node_modules/sass-loader/lib/loader.js):

.#{$class-prefix}-btn {
  ^
      Undefined variable: "$class-prefix".
      in /Users/yangmei/CloudStation/coding.net/HWL/nautilus-ui-pro/node_modules/vue-atlas/src/Button/VaButton.vue (line 362, column 4)

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-atlas/src/Button/VaButton.vue?vue&type=style&index=0&lang=scss& 4:14-378 14:3-18:5 15:22-386
 @ ./node_modules/vue-atlas/src/Button/VaButton.vue?vue&type=style&index=0&lang=scss&
 @ ./node_modules/vue-atlas/src/Button/VaButton.vue
 @ ./node_modules/vue-atlas/src/Button/install.js
 @ ./node_modules/vue-atlas/src/Button/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.29.33.191:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by mrdionjr** [comment]
I'm facing the same issue, I've taken a look at the source code for the dropdown component and it seems like the variable is not imported nor defined anywhere. This issue affects all the components listed on the "import individual component" section. Please provide support for this as importing the whole library is not wise. Thanks

**Comment by nvms** [comment]
I have a solution for this, but I won’t be able to work on it until I return from travel in about a week.

my proposed solution is to simply remove the `$class-prefix` variable entirely from SCSS as well as the `prefixCls` prop from all components. if you need this change sooner than that, please submit a pull request with this change and I’ll gladly review it.

**Comment by mrdionjr** [comment]
Thanks for your quick reply. I tried to only import the dropdown component and declare the variable ($class-prefix: 'va') in the component file in node_modules. But it does not solve the issue. There are other undefined variables like: $N0 and $P700. I could not figure out what's wrong since I didn't cloned the repo. This issue require a closer look and should be put on high priority. I'm planning to use this library for my next project and I really need this feature. I would happily work on it if you can give me some directions.

**Comment by mrdionjr** [comment]
However, one way we could solve is to keep only abstract style (variables, mixins, functions) in the style folder. Then import it in the default.scss file. Then import this file in every component. That's how it done in [Vue enterprise boilerplate](https://github.com/chrisvfritz/vue-enterprise-boilerplate)

**Comment by nvms** [comment]
ah yes, $N__, $B__, $R__ and the rest are all of the color definitions you can find in `/src/style/_colors.scss`. those should be the only remaining undefined variables used. the import method you suggest is ideal and likely will be what is done.

`/src/style/default.scss` currently imports that file as well as a few others. it imports `_font.scss`, which is rather large. I’d probably opt to remove that import statement and instead import it directly in `VaIcon.vue`, where it is actually used.

admittedly, yes, the style architecture for this library could stand to be improved significantly.

**Comment by mrdionjr** [comment]
Yes, I was finally able to get this working by importing the variables.scss file, which imports the colors, in the dropdown component. I can work on the proposed architecture if you agree.

**Comment by mrdionjr** [comment]
Great I'll wait for you then, I'm setting up the project. Let me know if you need someone to help either testing or documentation.

**Comment by nvms** [comment]
haven't forgotten about this - latest release removed all reference to `classPrefix` prop and `#{$class-prefix}` SCSS variable.

will work on reorganizing imports next

**Comment by nvms** [comment]
imports reorganized

now, for example, you can just:

```javascript
import { VaDatepicker } from "vue-atlas/src/Datepicker";

Vue.use(VaDatepicker);
```

the styles needed for the component to work are now just contained or imported by the component, but this does of course mean that `node-sass` and `sass-loader` will need to be available.

also, this has been done as well:

> it imports _font.scss, which is rather large. I’d probably opt to remove that import statement and instead import it directly in VaIcon.vue, where it is actually used.

sorry this took so long. I believe this can be closed.
