### ISSUE TITLE
[Feature Request] Breadcrumb Component

### ISSUE THREAD

**Issue by lopermo** [nvms/vue-atlas#141]
**Brief overview of the component. What does it do?**
Breadcrumb component, self explanatory. It's already designed, would be nice to have in the docs as well as a standalone component.

**Why is this component needed?**
It's included under the the "Page Header Component", but not as a standalone component in the docs.

[Check it out here](https://vue-atlas.com/documentation/pageheader)

**Comment by nvms** [comment]
been meaning to get around to this. I’ll put it on the radar. thanks for the reminder!

**Comment by nvms** [comment]
this is done (finally)
