### ISSUE TITLE
Components are not mobile friendly

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#15]
Hi. 
Hard to scroll any page on iOS. Almost not possible.
Hamburger menu not work. After click it becomes in hover state, but menu not appears.

**Comment by nvms** [comment]
Yes, the hamburger menu on the documentation page is indeed broken at the moment. It will be fixed shortly.

I'll have to get an iOS device to test out the scrolling issue. Can you explain more what you mean by it is almost not possible?

**Comment by rejifald** [comment]
@nvms I will attach video after few minutes.

**Comment by rejifald** [comment]
@nvms [https://drive.google.com/open?id=12cHyz-MlnMOOqWN96Io8T8Dvsyl68FDM](example)

**Comment by nvms** [comment]
The hamburger should be working now. Thanks for reporting that - I had not noticed that I broke it!

**Comment by nvms** [comment]
Hmm.. Thanks for the video, it helps a lot. I'm not sure what's going on with the scrolling there, but I'll dig into it this weekend.

**Comment by rejifald** [comment]
@nvms this is some debug info for u [video](https://drive.google.com/open?id=1b6mbDPwFKueeDCdOU01LZ982jbPlmDyx). I have showed what block is scrolled instead of page.

**Comment by nvms** [comment]
thank you, I will take a look this evening

**Comment by rejifald** [comment]
@nvms NP. U can write me, if u will be need more info. I can debug on iOS, macOS.

**Comment by nvms** [comment]
thanks again for the video - very helpful. the scrolling issue is fixed.
