### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by davidlinc1** [nvms/vue-atlas#155]
Hello there! Loving this project, great work.

I'm wondering if the documentation found at https://vue-atlas.com/documentation/ will be made available as a part of the project? I was a little disappointed to see that what you get after installing is a single-page sandbox that shows off dropdowns, notifications, modals and an alert, but doesn't feature the full docs as seen on the vue-atlas.com website.

https://i.imgur.com/54h5XJD.png

Is there a reason for this?

**Comment by nvms** [comment]
Hello, and thank you!

There is a reason that the documentation website hasn't been made public, but it's not a very good one. That project is an absolute mess. It needs a ton of attention. It needs to be rebuilt from the ground up, honestly. I built it alongside atlas as it, at the time, also served as my sandbox/test environment. It turned into an unwieldy beast.

It will be rebuilt, and it will be made public. Hopefully soon.

**Comment by davidlinc1** [comment]
Very cool, thanks for the clarification!

**Comment by lighth7015** [comment]
How is the documentation rewrite going, if at all?
