### ISSUE TITLE
Prevent theme propagation into child components.

### ISSUE THREAD

**Issue by PaulRaUnite** [nvms/vue-atlas#156]
Hi! I try to create a dropdown with an input field on topbar (some sort of inline sign-in dialog) but topbar theme affects input's style. Is there any option to disable this type of behaviour? (I tried to explicitly pass theme to input component but it has no effect)

The code sample:
```vue
<va-topbar theme="dark">
    <div slot="right">
        <va-dropdown>
            <div slot="trigger">
                <va-button type="darker">
                </va-button>
            </div>
            <va-input/>
        </va-dropdown>
    </div>
</va-topbar>
```

Thank you in advance.

**Comment by nvms** [comment]
hello!

thanks for catching this and sorry for the late reply. I'll more directly scope this style declaration so that it's only applied if the input is the direct descendant of the topbar. you can expect a new release today with this change.

**Comment by nvms** [comment]
<img width="270" alt="Screen Shot 2019-12-27 at 10 13 58 AM" src="https://user-images.githubusercontent.com/17074357/71527906-3d7a8f80-2892-11ea-9eb8-c91508501828.png">

`2.1.8` was just pushed to npm with this change
