### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#16]
Hi All.
I have tried build project locally, but seems like necessary `webpack.build.js` config are not presented.
How can I contribute ?

**Comment by nvms** [comment]
You'll probably want to start a new project using `vue-init webpack MyProject`. After that, just `npm install vue-atlas` and follow the quickstart guide on the documentation. It should build just fine.

**Comment by rejifald** [comment]
@nvms nope. I like this project. And I want to fix some bug. I have cloned repo, but I can't run it.

**Comment by nvms** [comment]
The repository in its current state is meant to be used as a node module. At the end of the day, these are just single-file Vue components that can be used in any Vue project. You can include them into any of your Vue projects just as you normally would include your own Vue SFCs. I'd recommend starting a new project using `vue-init`, and cloning the repository into a directory of your choosing, and importing the components manually using Vue's plugin system.

**Comment by rejifald** [comment]
@nvms I understand. Thanks.
