### ISSUE TITLE
Implement momentum-based scrolling for a more native feel on iOS devices, incuding Sidebar

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#17]
Page container has 100% height, but page content almost always is bigger. So page content overflows page container. Is it ok ?

**Comment by nvms** [comment]
The Page component's dimensions are such that it takes up the space of the window, minus the dimensions of the Sidebar, Minibar and Topbar. It's common that the content of the Page component will overflow its dimensions. It's expected. It should become scrollable when this happens. Are you seeing some weird behavior?

**Comment by rejifald** [comment]
Page does, but page container shouldn't. I think. [Screenshot](https://drive.google.com/open?id=10CL_QUiotbKnFb2T_ckJ04wiiZQOtEr6)
But yes, scroll behavior little weird. It is not smooth like regular site.
I mean regular site - is site where height of content are bigger than viewport.
In this case page has 100% height of viewport. So its content is overflowed. Therefore scroll is not good.
Maybe I am wrong.

**Comment by nvms** [comment]
I see what's happening in the screenshot, and it's definitely an easy fix. Although this shouldn't affect scrolling behavior at all.

I have not noticed any issues with scrolling not being smooth. I personally believe that scroll behavior (e.g. speed, fake smoothing) should never be changed, so I won't do it.

**Comment by rejifald** [comment]
I am saying about default scroll behavior. Here is [example](https://drive.google.com/open?id=1i3yeqg8JLyI4TLIRzjIhrk2OLfwgdcok)

**Comment by nvms** [comment]
Ohhh, yeah, I see that. I have no idea why that is happening. I'll look into this.

Just tested this on an iOS device using Safari, and an Android device using Chrome. I can reproduce this on the iOS device but not on the Android device.

Again, no idea why that is happening. Thoughts?

**Comment by nvms** [comment]
Looks like `–webkit-overflow-scrolling: touch` might be the solution - I'll do some testing.

**Comment by rejifald** [comment]
Yes. I think I know whats happening.
I think this because of browser render flow.
Elements with clipped content doesn't render that clipped content.
Exception only whole HTML document.
For example: 
1. Body element has height 99999px - smooth scrolling, because page rendered at once and just moving from top to bootom when u scroll
2. Body element 100% of viewport, but it child has height 99999px - in this case 99999px - 100%viewport height won't rendered immediately.

**Comment by nvms** [comment]
[This Mozilla article](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling) talks about "momentum-based scrolling, where the content continues to scroll for a while after finishing the scroll gesture and removing your finger from the touchscreen. The speed and duration of the continued scrolling is proportional to how vigorous the scroll gesture was."

I'm looking into the best way to implement this so things feel more... native. Annoyingly enough, this seems to be only an issue on iOS devices and fixed or absolutely positioned elements. Android seems to handle this type of momentum-based scrolling behavior just fine on fixed or absolutely positioned elements.

**Comment by rejifald** [comment]
Yes, I see ! Fantastic !
NP :)

**Comment by rejifald** [comment]
@nvms Can u do the same on menu component ?
Maybe, this should be done in all scrollable places, like menus, dropdowns.
But dropdowns probable will be replaced by native ones.

**Comment by nvms** [comment]
Will move this functionality over to the Sidebar as well.

**Comment by nvms** [comment]
done in 0f5c3d5
