### ISSUE TITLE
Non-scrollable demo of the LayoutManager

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#18]
1. Go to [LayoutManager](https://vue-atlas.com/documentation/layoutmanager)
2. Click the button in the middle of the page, to the right
3. Try to scroll opened modal

**Comment by nvms** [comment]
It now scrolls. The documentation page was using an old build of vue-atlas. This was an issue that you would not have in the more recent versions, if you were to install from npm. Anyways, it's fixed now. Thanks for the report!

**Comment by nvms** [comment]
Actually... _**now**_ it's fixed. Forgot to push to production.

**Comment by rejifald** [comment]
@nvms Yes ! I see now.
