### ISSUE TITLE
Controls don't respond to tab focus

### ISSUE THREAD

**Issue by ffpetrovic** [nvms/vue-atlas#2]
The Datepicker doesn't expand on focus ( by tabbing ) and neither does the Dropdown for that matter
Is this a mistake or can we somehow enable it?   

Thanks!

**Comment by nvms** [comment]
This has been implemented and pushed out in the last release. Nearly all controls now respond to tab focus; Datepicker and Timepicker and Select can be expanded by pressing Enter.

**Comment by ffpetrovic** [comment]
A suggestion would be to allow navigation of those components with arrow keys. Thanks for the new features!

**Comment by nvms** [comment]
A good suggestion. I'll work on that next.
