### ISSUE TITLE
new props for dropdown

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#22]
I think prop "trackBy" and "label" will be very useful for dropdown.
First of all, because many dropdowns are used with collections of objects.
And for compare value specified in v-model prop and value in options list.
So, just for setting this two props, i can easily generate dropdown.

**Comment by nvms** [comment]
Can you explain what the `label` prop is meant to be used for? That is unclear to me.

Also, if I understand correctly, `trackBy` would be an array of objects passed to the Dropdown component? I assume you'd like the Dropdown component to build a list of items based on the values passed in by the `trackBy` prop? Is that right? I could see how this behavior would be helpful, but I'm not sure I understand why the prop would be called `trackBy`, as opposed to something self-descriptive, like `items` or `listItems` - or something along those lines.

**Comment by rejifald** [comment]
No. Let me explain. 
For example, we have foew options from mongo. 
They represented as array
‘[{id:1, name:Company 1},{id:2, name: Company 2},{id:3, name: Company 3}]’. 
How We can build list of options from it ?
We can declare component ‘<va-dropdown v-model=“choosenCompany” :options=“companiesList” label=“name” trackBy=“id”></va-dropdown>’
That component will build list of options by self. 
But what purpose of trackBy field ? This is because we can’t compare objects directly by their memory address. We can compare they by trackBy field, and mark this option like already selected. 
So, if company variable from v-model will be ‘{id:1, name:Company 1}’ we can find appropriate option in list, by comparing with trackBy field,

**Comment by nvms** [comment]
Would you be willing to submit a PR for this? I'd like to see an example if possible.

**Comment by rejifald** [comment]
> Would you be willing to submit a PR for this? I'd like to see an example if possible.

Sure. I am little busy now. I will try do this on next weekend.
