### ISSUE TITLE
Va-select and v-for with va-option

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#23]
There is a problem with building options using v-for:

```
optionsList = [ { name : "1", value: "1" }, { name : "2", value: "2" } ];

<va-select v-model="simpleValue" placeholder="Select" no-uncheck>
   <va-option :v-for="item in optionsList" value="item.value">{{ item.name }}</va-option>
</va-select>
```

In this case inner `li a` element wrapper around option is not build so there is no padding of item:

<img width="169" alt="screen shot 2018-11-13 at 11 35 37 pm" src="https://user-images.githubusercontent.com/24208746/48444630-21ef1b00-e79d-11e8-8e0a-1f2b8959b46d.png">

**Comment by nvms** [comment]
This just comes down to basic Vue stuff, and not really specific to atlas.

A `v-for` should be written as such, and not with a color preceding it, like you have above: `:v-for`.

Also, in your VaOption declaration, you are passing the literal string "item.value" to value. I would image you'd want to pass the value of `item.value`, in which case you'll want to precede the call with a colon, like this: `:value="item.value"`.

You'll want to use templating for something like this. Here's a working example with `v-for`:

```
<va-select v-model="simpleValue" placeholder="Pick an animal" no-uncheck>
  <template v-for="animal in animals">
    <va-option :value="animal.value" :key="animal.value">{{animal.label}}</va-option>
  </template>
</va-select>
```

I suggest checking out the Vue documentation for the `template` tag.

Here's that `animals` array used in the example above:

```
animals: [
        { value: 'cat', label: 'Cat' },
        { value: 'dog', label: 'Dog' },
        { value: 'wallaby', label: 'Wallaby' },
        { value: 'bear', label: 'Bear' },
        { value: 'kangaroo', label: 'Kangaroo' }
      ]
```


---


![example](https://user-images.githubusercontent.com/17074357/48445685-fd1e8780-e74b-11e8-96f4-11e82b665461.png)
