### ISSUE TITLE
Import by Component to save  bundle size [Enhancement]

### ISSUE THREAD

**Issue by patrickcurl** [nvms/vue-atlas#24]
I think it'd be nice if you could just pull out what you need to use, to limit webpack bundle size and what not...

**Comment by nvms** [comment]
hello, this feature is nearly finished and will be merged soon.

**Comment by patrickcurl** [comment]
@nvms awesome, good to hear!

**Comment by nvms** [comment]
@patrickcurl this feature has been added and is included in the latest npm package.
