### ISSUE TITLE
Align page header actions with title

### ISSUE THREAD

**Issue by marvinrabe** [nvms/vue-atlas#28]
The actions of the page header are currently aligned with the bottom slot.

For better consistency with the Atlasian layouts align bottoms to the title instead.

See: https://atlaskit.atlassian.com/packages/core/page-header

**Comment by nvms** [comment]
that's actually how it was for a while, before I changed it to the way it is now. I changed it because of personal preference. maybe we can introduce this as a boolean prop?

**Comment by nvms** [comment]
this is done and added to the latest npm package
