### ISSUE TITLE
Build scripts are broken

### ISSUE THREAD

**Issue by marvinrabe** [nvms/vue-atlas#29]
There is currently no way to build this library on my own.

The `build` folder seems to be missing.

**Comment by nvms** [comment]
added `build` folder with build scripts, as well as:
- `webpack.config.js`
- `.babelrc`
- `.eslintignore`
and..
- `.postcssrc.js`

you should now be able to clone the repository, `npm install` dependencies and run any of the builds scripts to build the project.

thanks for the issue - closing it now
