### ISSUE TITLE
Accessibility: escape to close

### ISSUE THREAD

**Issue by nvms** [nvms/vue-atlas#4]
Pressing escape should close/hide an active/open Dropdown, Select, Timepicker and Datepicker.

**Comment by marvinrabe** [comment]
Maybe the same for Modal and Aside?

I can do this if you like.

**Comment by nvms** [comment]
Indeed, escape should close those as well.

For the Modal, when they are stacked, I'm thinking that escape should only close the topmost Modal.

Feel free to work on this! Much appreciated.

**Comment by nvms** [comment]
Hi,

I'm closing this issue. Not because it is complete; it is not. I'm closing it because I'm breaking this out into a number of separate accessibility issues, making this a duplicate.
