### ISSUE TITLE
disable inheritAttrs where acceptable and instead bind $attrs to relevant element

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#43]

**Comment by max-frai** [comment]
Yes, +1 for this on

**Comment by nvms** [comment]
would `min` and `max` be in reference to the allowed number of characters of the input's value?

**Comment by rejifald** [comment]
Yes. I actually would like to suggest disable [inheritAttrs](https://vuejs.org/v2/api/#inheritAttrs) option in all components, where it is possible, and use instead $attrs property, to bind them to expected component.
For example i can't set autocomplete property to input, also min and max attributes as well.

**Comment by nvms** [comment]
ah yes, understood. good catch. this will get done asap.

**Comment by nvms** [comment]
<img width="417" alt="source" src="https://user-images.githubusercontent.com/17074357/52451631-9dd6d600-2af4-11e9-82d2-f7b2f33be158.png">

<img width="608" alt="markup" src="https://user-images.githubusercontent.com/17074357/52451638-a16a5d00-2af4-11e9-9057-bf3b7c62589e.png">

this behavior is implemented for the input component. I'm looking for other places this might be needed. open to suggestions.

**Comment by rejifald** [comment]
Amazing !

**Comment by rejifald** [comment]
All inputs, datepicker, textarea, etc.
Form itself. 
label, i think it’s important to provide for attribute at least. Because sometimes we need to follow common rules in building forms. To provide ability browsers or password managers correctly with our forms.

**Comment by rejifald** [comment]
Also tables, buttons. 
And everywhere where we may use aria-* attributes

**Comment by nvms** [comment]
I think I can say this is done now. if you notice anything I've missed please let me know.
