### ISSUE TITLE
FR add prefix and postfix to inputs

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#44]
Hi. I think it will be great to have ability change type of entered value.
For example if u enter 10.05 and u want set that this is EUR currency.
Or u may enter 10 and set that this THz, or just Hz, whatever.

**Comment by nvms** [comment]
this is a nice idea, I'll keep it in mind for a near future release

**Comment by nvms** [comment]
this has been implemented and will be available in the next release

source:
<img width="325" alt="screen shot 2019-02-08 at 12 31 09 pm" src="https://user-images.githubusercontent.com/17074357/52504481-7ee04e80-2b9d-11e9-9d1c-6550bf760703.png">

result:
<img width="424" alt="screen shot 2019-02-08 at 12 25 29 pm" src="https://user-images.githubusercontent.com/17074357/52504502-856ec600-2b9d-11e9-916a-3b4ac6541a45.png">
