### ISSUE TITLE
documentation page bug: Alert types ignored

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#49]
(Alert documentation)[https://vue-atlas.com/documentation/modal] says "Based on the type you choose, a relevant icon will be shown to the left of the title. "
But seems like there no difference.

**Comment by nvms** [comment]
this is a bug specific with the documentation website that I'm still working on, and is not an issue in the production version of the package - go ahead and test it out in your own project and you'll see that this is the case.

**Comment by rejifald** [comment]
Yes, it works ! Thanks.

**Comment by nvms** [comment]
bug fixed on documentation page

solution: migrated the documentation from old webpack build pipeline to new vue-cli-service build pipeline
