### ISSUE TITLE
Components shifting when reevaluated by HMR

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#50]
After each change nuxt^2.0.0 layout looks like i have sidebar. But i don't. After manually reload page in browser everything looks fine, again.
I can provide u screenshots, or video.

**Comment by nvms** [comment]
I'm not very familiar with nuxt, so I'm not sure what could be happening.

does the `.va-sidebar ` element actually get removed from the page?
does this happen every time you save any change?

`VaApp` keeps track of where things should be positioned. at the moment, there aren't checks in place to update the layout position when the `VaSidebar` component is removed from the page, because that really shouldn't be happening.. ever..

**Comment by rejifald** [comment]
I believe that this not because nuxt itself, i guess it related to hot-reload feature in common. 
I don’t have sidebar in my layout at all. My layout is minibar and page component. But every time after any changes i return back into browser and i see that my layout looks like i have sidebar and it’s empty. 
I will try to capture video

**Comment by rejifald** [comment]
There is example.
https://drive.google.com/open?id=16gQqc2r9MDF6Pk0oCfQY9SCpgA3U-rK5

**Comment by rejifald** [comment]
And i never had sidebar in this project

**Comment by nvms** [comment]
ah okay, pretty sure I know why this is happening. I'll work on this a bit later tonight. thanks for the clear example

**Comment by nvms** [comment]
I can't reproduce this, but I think I may have fixed it in commit 6abdc1c

it'll be live in the next release.. probably this weekend

**Comment by nvms** [comment]
actually no, probably not.. it seems in your example that somehow VaPage is being unmounted and remounted.. it makes sense to me now what is happening. I'll have to come up with a better solution

**Comment by nvms** [comment]
8a6e04b fixes this

**Comment by rejifald** [comment]
Update: this bug appear also while navigation. Can u update package with this fix, please ?

**Comment by nvms** [comment]
can you clarify?

**Comment by rejifald** [comment]
U fixed this bug already :)
I just asked u to update package because i found that this bug affects not only HMR, but also page loading, after going from one page to another page.
But now it's gone.

**Comment by nvms** [comment]
ahh okay, gotcha. thanks for letting me know
