### ISSUE TITLE
Form validation reset

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#64]
Hi! When I call `form.validateFields` it works okay, but after some success logic I want to reuse overall form again so I reset input data fields in code, this causes validation again and fields become red.
How to "cancel" validation on form?

**Comment by nvms** [comment]
added in 6bd7b48

you will want to call `this.$refs.myForm.resetValidation()` to clear validation status. please upgrade to 2.0.6 (will be released in a few minutes) so that this will be available in your project

**Comment by max-frai** [comment]
You are amazing :)
