### ISSUE TITLE
VaSelect - value must be string

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#69]
Hi. 
I found this https://github.com/nvms/vue-atlas/blob/cd81da1ad3428d5110e863772ffb922f491ef46b/src/Select/VaOption.vue#L16
I believe that value can be not only string, but any other JS type. Including object.
I don't see reason why it should be restricted. Especially if label prop exists.
So i may want to have value as Object, or as Number.
It's real problem that i have now. I want to have value as Number.
WDYT ?

**Comment by nvms** [comment]
this is a good idea. added in 91a4ee6. will update documentation sometime today
