### ISSUE TITLE
Input: events don't bubble

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#74]
Not working
```
            <va-input @keyup.enter="handleSubmit"/>
```
working
```
            <input @keyup.enter="handleSubmit">
```

**Comment by nvms** [comment]
stupid mistake on my part, forgot to emit this event after intercepting it.. fixed in 9570897

**Comment by nvms** [comment]
by the way, THANK YOU for finding all of these issues and bringing them to my attention.. the library is improving a lot because of this

**Comment by rejifald** [comment]
No problem ! I like work with u too :)
