### ISSUE TITLE
Docs: Add info about prefix&postfix on input

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#79]
Hi! I had to search through issues to find one related to prefix on inputs and how to use them #44 .
Unfortunatelly, this info is missing on input docs. It would be great to add samples for the newcomers.

**Comment by max-frai** [comment]
<img width="367" alt="default" src="https://user-images.githubusercontent.com/24208746/53090330-be048d00-3517-11e9-92ab-e8c901855a9b.png">
Also I think there is problem with prefixes when You made inputs inherit width (and it's 100% by default now).

**Comment by nvms** [comment]
good catch! I'll do the write-up today.

**Comment by nvms** [comment]
this is done

**Comment by max-frai** [comment]
Amazing. Can we donate you somehow? Paypal, cryptocurrencies? :)

**Comment by nvms** [comment]
wow I appreciate that! I haven't actually considered this. maybe I will look into it some day :)
