### ISSUE TITLE
Elements in one line without form

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#81]
Is it possible to make, for example, input and button be on one line taking all 100% space without form? Because this case generates unneeded label.
<img width="592" alt="default" src="https://user-images.githubusercontent.com/24208746/53099539-ad134600-352e-11e9-8109-550200a05d71.png">

**Comment by nvms** [comment]
it seems like you want to wrap these in a flex box

```html
<div style="display:flex;">
  <va-input /><va-button>btn</va-button>
</div>
```

there is not currently a component that does this for you. I'm not sure the use case is significant enough to justify creating one
