### ISSUE TITLE
Search in Select does not work for dynamic va-options

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#84]
When Select is constructed like this (from docs), search field does not filter list. 
```
<va-select v-model="animalValue" placeholder="Pick an animal" no-uncheck search>
  <template v-for="animal in animals">
    <va-option
      :key="animal.value"     
      :value="animal.value"
      :label="animal.label">
      {{animal.display}}
    </va-option>
  </template>
</va-select>
```
When the list is passed with `options` attribute, it works.

**Comment by nvms** [comment]
this made me realize that search filtering does not work when passing `va-option` children to the default slot of `va-select`.

can you explain your use case, and why you need to pass these using `v-for` instead of using the `options` prop, e.g.:

`<va-select v-model="animalValue" :options="animals" search />`

**Comment by max-frai** [comment]
For example, when my data is not in format of options `va-select` needs. Of course, I can write `computed` over my property and modify it, but I decided to use v-for

**Comment by nvms** [comment]
I'll update the documentation to note that the `search` prop should only be used when passing options via the `options` prop.

it's possible to change this behavior, but it is quite a significant change and I don't know if I'll be able to get around to it any time soon. I'm open to contributions for this.

in the meantime.. I'm not considering this a bug. instead, I see this is a result of choosing to use the Select component one way over another. you can quickly get search working by, as you said, formatting your data in such a way that it is accepted by the `options` prop.

I'm closing this, but again, I would welcome a contribution that modifies this behavior as long as it doesn't break anything else. thanks!
