### ISSUE TITLE
Toggle icon

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#88]
Ability to set icon which will be showing on hover. It's handful in case when u are showing actual icon, and want replace it to delete icon, for example. WDYT ?

**Comment by nvms** [comment]
I'm open to the idea.. any suggestions on how this might be implemented?

the current Icon component is used heavily throughout the library, so it needs to remain compatible

**Comment by rejifald** [comment]
I understand. I suggest add new, for example “hover-icon”, and if it present, then take it value, run fadeOut transition, replace icon, run fadeIn transition.

**Comment by rejifald** [comment]
And it should be compatible, anyway

**Comment by rejifald** [comment]
I have better solution. Instead of changing existing icon component - create new component, that will have few events to toggle, just like Tooltip. Probably also transition settings.

**Comment by nvms** [comment]
I'm not sure I fully understand. maybe you could provide an example

**Comment by nvms** [comment]
#92 was merged
