### ISSUE TITLE
[Feature request] VaButton should accept prefix and postfix icons

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#89]
I think there many use cases where it may be

**Comment by nvms** [comment]
agreed - will work on this tonight

**Comment by nvms** [comment]
please clarify what you mean by "button" in the title

are you suggesting that `va-input` should somehow accept a `va-button` for the `prefix` and `postfix` props?

**Comment by rejifald** [comment]
No, i mean, buttons like this.
![image](https://user-images.githubusercontent.com/42000283/53258403-3bc1c780-36d5-11e9-9f4c-7ae03951bb04.png)
https://evergreen.segment.com/components/button/

**Comment by max-frai** [comment]
I think more general way: use va-icon inside button text is enough here and no need for separate config on button

**Comment by rejifald** [comment]
It won't give u desired effect. Icon always should be at the start, or at the end. 
When u place icon before\after text, u will have just ugly button, with icon just before/after text. U will need set gaps, alignment, and so on.

**Comment by nvms** [comment]
@rejifald this is why the margin prop exists for the `va-icon`. alternatively, just set the style of the icon such that it pushes the text over a bit. @max-frai's approach is very common implementation that I use frequently.

```html
<va-button>
  Icon after
  <va-icon type="angle-right" margin="0 0 0 7px">
</va-button>
```

I cannot see a reason to introduce an entire component to do the above.

**Comment by rejifald** [comment]
It won't behave as `justify-content: space-between`

**Comment by nvms** [comment]
indeed, it will not. I'm not opposed to changing this:
https://github.com/nvms/vue-atlas/blob/master/src/style/_button.scss#L428

to `justify-content: space-between`, as it doesn't seem to visually affect anything else as far as I can tell.

**Comment by nvms** [comment]
hmm, well.. on larger buttons the `space-between` solution might not be ideal. the icon would be in the right spot, sure, but the text would no longer be centered.

I can understand the need for this now.

a clear, specific explanation from the beginning and I may have reached this conclusion much sooner without having to work through it myself  😄

I'll work on a solution similar to Evergreen's implementation.

**Comment by nvms** [comment]
this is what I have so far. icons are defined as such:

`<va-button icon-before="home" icon-after="question" />`

<img width="406" alt="screen shot 2019-02-22 at 1 27 24 pm" src="https://user-images.githubusercontent.com/17074357/53272306-c12d8380-36a5-11e9-984e-8f6d699e8bfc.png">

feedback? requests?

**Comment by rejifald** [comment]
Looks great ! 
One suggestion is: don't reserve space for two icons, when actually u have one icon.
I think there can be something like 
```
<va-button icon-before="home" :icon-after="false" />
```
And, button will looks like 
![image](https://user-images.githubusercontent.com/42000283/53272493-28752300-36fa-11e9-856c-7a2d83694f6f.png)

**Comment by rejifald** [comment]
Just like evergreen icon-buttons.

**Comment by nvms** [comment]
gotcha, I'll work on that

**Comment by nvms** [comment]
<img width="325" alt="screen shot 2019-02-22 at 2 07 07 pm" src="https://user-images.githubusercontent.com/17074357/53274192-394a7800-36ab-11e9-9aba-23cc07f9fe4a.png">

anything I'm missing?

**Comment by rejifald** [comment]
Nope. Great !
