### ISSUE TITLE
Docs for development mode

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#91]
It would be great if you write some DEVELOP.md doc for setting up development&debug cycle. I'm  glad to fix some issues by myself and don't disturb you.
I'm relative new to npm and js development process so I don't know what's the right way to set up vue-atlas independently and test it.

**Comment by nvms** [comment]
good idea. I'll get something written up as soon as time permits

**Comment by rejifald** [comment]
Just make fork of this repo
Install dependencies
Type `npm run serve`
Look in console. There will be address of ur local server. 
U will see App.vue component on the main page at this address. 
Just add component which u want to test to App.vue, or u can just modify existing. 
That’s all.

**Comment by nvms** [comment]
please see [CONTRIBUTING.md](https://raw.githubusercontent.com/nvms/vue-atlas/master/.github/CONTRIBUTING.md) for basic instructions on getting started with contributing

**Comment by rejifald** [comment]
I think u can add link to this doc to main readme file.
